const chemicals = [
  {
    id: 1,
    name: "MADAR Foam Spray",
    manufacturer: "Not specified",
    type: "Flammable, gas, health",
    expiry: "12/11/2026",
    status: "Valid",
    hazard: ["Flammable", "Gas Under Pressure", "Health Hazard"],
    sds: "https://drive.google.com/file/d/1GnCaU6AYcpJkkLAbUvgl9vXmdfZfAK4z/view?usp=sharing",
    coshh: "COSHH/MADAR Foam Spray.pdf"
  },
  {
    id: 2,
    name: "ANCHOR SPRAY PAINT",
    manufacturer: "Not specified",
    type: "Flammable, Health, Environment",
    expiry: "10/09/2026",
    status: "Valid",
    hazard: ["Flammable", "Health Hazard", "Hazardous to Environment"],
    sds: "https://drive.google.com/file/d/1m8Y8ixzri57kwP8OVeal6gykbO6xPuBP/view?usp=sharing",
    coshh: ""
  },
  {
    id: 3,
    name: "ANCHOR SPRAY PAINT",
    manufacturer: "Not specified",
    type: "Flammable, Health, Environment",
    expiry: "09/07/2026",
    status: "Expired",
    hazard: ["Flammable", "Health Hazard", "Hazardous to Environment"],
    sds: "https://drive.google.com/file/d/1m8Y8ixzri57kwP8OVeal6gykbO6xPuBP/view?usp=sharing",
    coshh: ""
  },
  {
    id: 4,
    name: "Sikadur 31/41 cf slow 2 liter part A 3141",
    manufacturer: "Not specified",
    type: "Health",
    expiry: "11/10/2027",
    status: "Valid",
    hazard: ["Health Hazard"],
    sds: "https://drive.google.com/file/d/1yAbU0mZH1uHt/view?usp=sharing",
    coshh: ""
  },
  {
    id: 5,
    name: "Sikadur 31/41 cf slow 1 liter part B 3141",
    manufacturer: "Not specified",
    type: "Corrosive",
    expiry: "09/07/2026",
    status: "Expired",
    hazard: ["Corrosive"],
    sds: "https://drive.google.com/file/d/1yAbU0mZH1uHt/view?usp=sharing",
    coshh: ""
  },
  {
    id: 6,
    name: "Engin Oil ( Shell Helix HX5-15W-40 ) EACH 4 LITTER",
    manufacturer: "Not specified",
    type: "Environment",
    expiry: "08/07/2028",
    status: "Valid",
    hazard: ["Hazardous to Environment"],
    sds: "https://drive.google.com/file/d/1bY00Xygs7rQar/view?usp=sharing",
    coshh: ""
  },
  {
    id: 7,
    name: "WD - 40",
    manufacturer: "Not specified",
    type: "Health, Flammable, Gas cylinder",
    expiry: "09/07/2028",
    status: "Valid",
    hazard: ["Health Hazard", "Flammable", "Gas Under Pressure"],
    sds: "https://drive.google.com/file/d/10Bj0bMYG1dnZ/view?usp=sharing",
    coshh: ""
  },
  {
    id: 8,
    name: "HILTI RE-500 V4 /500 MODLE : 2287554",
    manufacturer: "Not specified",
    type: "Corrosive, Environment",
    expiry: "10/07/2028",
    status: "Valid",
    hazard: ["Corrosive", "Hazardous to Environment"],
    sds: "https://drive.google.com/file/d/1hefPZPDWbyPB/view?usp=sharing",
    coshh: ""
  },
  {
    id: 9,
    name: "FISHER CHEMICAL",
    manufacturer: "Not specified",
    type: "Health, Corrosive",
    expiry: "11/07/2028",
    status: "Valid",
    hazard: ["Health Hazard", "Corrosive"],
    sds: "https://drive.google.com/file/d/1wvNzY5lYnCj5l6/view?usp=sharing",
    coshh: ""
  },
  {
    id: 10,
    name: "GREASE, ORDINARY SIZE10: 15 KG/PAIL MP2 ( PER BUCKTS 15KG )",
    manufacturer: "Not specified",
    type: "Environment",
    expiry: "12/07/2028",
    status: "Valid",
    hazard: ["Hazardous to Environment"],
    sds: "https://drive.google.com/file/d/1Nt0wqWIFP10IA/view?usp=sharing",
    coshh: ""
  },
  {
    id: 11,
    name: "Weber Curing Y20",
    manufacturer: "Not specified",
    type: "Environment, Health",
    expiry: "13/07/2028",
    status: "Valid",
    hazard: ["Hazardous to Environment", "Health Hazard"],
    sds: "https://drive.google.com/file/d/1tHYeYIuAgltc84/view?usp=sharing",
    coshh: ""
  },
  {
    id: 12,
    name: "Admixtures Weber A244 RBA ( PER GALLON 20 LITTERS )",
    manufacturer: "Not specified",
    type: "Health",
    expiry: "14/07/2028",
    status: "Valid",
    hazard: ["Health Hazard"],
    sds: "https://drive.google.com/file/d/1USox_YD80d6L/view?usp=sharing",
    coshh: ""
  },
  {
    id: 13,
    name: "Petrol",
    manufacturer: "Not specified",
    type: "Flammable, Health",
    expiry: "15/07/2028",
    status: "Valid",
    hazard: ["Flammable", "Health Hazard"],
    sds: "https://drive.google.com/file/d/1fXFhmdJLmtu27/view?usp=sharing",
    coshh: ""
  },
  {
    id: 14,
    name: "Sika Mould Shutter oil",
    manufacturer: "Not specified",
    type: "Health, Environment, Flammable",
    expiry: "16/07/2028",
    status: "Valid",
    hazard: ["Health Hazard", "Hazardous to Environment", "Flammable"],
    sds: "https://drive.google.com/file/d/10E-pnSCt1N8ob/view?usp=sharing",
    coshh: ""
  },
  {
    id: 15,
    name: "Silicon",
    manufacturer: "Not specified",
    type: "Health",
    expiry: "17/07/2028",
    status: "Valid",
    hazard: ["Health Hazard"],
    sds: "https://drive.google.com/file/d/1VjHGCJNf_VXYge/view?usp=sharing",
    coshh: ""
  },
  {
    id: 16,
    name: "Vetobond PB434",
    manufacturer: "Not specified",
    type: "N/A",
    expiry: "18/07/2028",
    status: "Valid",
    hazard: [],
    sds: "",
    coshh: ""
  },
  {
    id: 17,
    name: "Weber jointseal pu 300",
    manufacturer: "Not specified",
    type: "Flammable, Environment",
    expiry: "19/07/2028",
    status: "Valid",
    hazard: ["Flammable", "Hazardous to Environment"],
    sds: "",
    coshh: ""
  },
  {
    id: 18,
    name: "SikaInject®-471 (MLNJECT 1315 PART A )",
    manufacturer: "Not specified",
    type: "Flammable",
    expiry: "20/07/2028",
    status: "Valid",
    hazard: ["Flammable"],
    sds: "",
    coshh: ""
  },
  {
    id: 19,
    name: "SikaInject®-471 (MLNJECT 1315 PART B )",
    manufacturer: "Not specified",
    type: "Enviroment",
    expiry: "21/07/2028",
    status: "Valid",
    hazard: ["Hazardous to Environment"],
    sds: "",
    coshh: ""
  },
  {
    id: 20,
    name: "Weberep Epo 412 CRY Plus A+B",
    manufacturer: "Not specified",
    type: "Health, Environment",
    expiry: "22/07/2028",
    status: "Valid",
    hazard: ["Health Hazard", "Hazardous to Environment"],
    sds: "",
    coshh: ""
  },
  {
    id: 21,
    name: "WeberPRIM EP 2KG A+B",
    manufacturer: "Not specified",
    type: "Health, Environment",
    expiry: "23/07/2028",
    status: "Valid",
    hazard: ["Health Hazard", "Hazardous to Environment"],
    sds: "",
    coshh: ""
  },
  {
    id: 22,
    name: "Weber Seal PS 1000 PG A+B",
    manufacturer: "Not specified",
    type: "Health, Environement",
    expiry: "24/07/2028",
    status: "Valid",
    hazard: ["Health Hazard", "Hazardous to Environment"],
    sds: "",
    coshh: ""
  },
  {
    id: 23,
    name: "SikaFlow 658",
    manufacturer: "Not specified",
    type: "Corrosive, Exclamation Mark",
    expiry: "25/07/2028",
    status: "Valid",
    hazard: ["Corrosive", "Health Hazard / Irritant"],
    sds: "",
    coshh: ""
  },
  {
    id: 24,
    name: "Permatreat TM PC 191T ( Berko Saf 106 )",
    manufacturer: "Not specified",
    type: "Health",
    expiry: "26/07/2028",
    status: "Valid",
    hazard: ["Health Hazard"],
    sds: "",
    coshh: ""
  },
  {
    id: 25,
    name: "Caustic Soda ( Sodium Hydroxide )",
    manufacturer: "Not specified",
    type: "Oxidizing, Environment, Health",
    expiry: "27/07/2028",
    status: "Valid",
    hazard: ["Oxidizing", "Hazardous to Environment", "Health Hazard"],
    sds: "",
    coshh: ""
  },
  {
    id: 26,
    name: "SMOOTH / GLOSSY PAINT WHITE & PASTELCOLORS ( Per Buckts 15 kg )",
    manufacturer: "Not specified",
    type: "Flammable, Health, Environment",
    expiry: "28/07/2028",
    status: "Valid",
    hazard: ["Flammable", "Health Hazard", "Hazardous to Environment"],
    sds: "",
    coshh: ""
  },
  {
    id: 27,
    name: "Wire Rope Spray",
    manufacturer: "Not specified",
    type: "Flammable",
    expiry: "29/07/2028",
    status: "Valid",
    hazard: ["Flammable"],
    sds: "",
    coshh: ""
  },
  {
    id: 28,
    name: "Setseal Flx Plus Liquid 5KG",
    manufacturer: "Not specified",
    type: "Flammable, Health",
    expiry: "30/07/2028",
    status: "Valid",
    hazard: ["Flammable", "Health Hazard"],
    sds: "",
    coshh: ""
  },
  {
    id: 29,
    name: "INSURE BOINDING 106S",
    manufacturer: "Not specified",
    type: "Flammable",
    expiry: "31/07/2028",
    status: "Valid",
    hazard: ["Flammable"],
    sds: "",
    coshh: ""
  },
  {
    id: 30,
    name: "Sikafloor 161 ( per drump 20 liters ) part A+b",
    manufacturer: "Not specified",
    type: "Corrosive",
    expiry: "01/08/2028",
    status: "Valid",
    hazard: ["Corrosive"],
    sds: "",
    coshh: ""
  },
  {
    id: 31,
    name: "Pipe joint lubricant",
    manufacturer: "Not specified",
    type: "Helath",
    expiry: "02/08/2028",
    status: "Valid",
    hazard: ["Health Hazard"],
    sds: "",
    coshh: ""
  },
  {
    id: 32,
    name: "Etch Primer",
    manufacturer: "Not specified",
    type: "Flammable, Corrosive, Health",
    expiry: "03/08/2028",
    status: "Valid",
    hazard: ["Flammable", "Corrosive", "Health Hazard"],
    sds: "",
    coshh: ""
  },
  {
    id: 33,
    name: "Fischer_531397_EN-GB_",
    manufacturer: "Not specified",
    type: "Health",
    expiry: "04/08/2028",
    status: "Valid",
    hazard: ["Health Hazard"],
    sds: "",
    coshh: ""
  },
  {
    id: 34,
    name: "JAZEERA Red JI-71001",
    manufacturer: "Not specified",
    type: "Flammable",
    expiry: "05/08/2028",
    status: "Valid",
    hazard: ["Flammable"],
    sds: "",
    coshh: ""
  },
  {
    id: 35,
    name: "JAZEERA RED OXIDE PRIMER JI-78005",
    manufacturer: "Not specified",
    type: "Flammable",
    expiry: "06/08/2028",
    status: "Valid",
    hazard: ["Flammable"],
    sds: "",
    coshh: ""
  },
  {
    id: 36,
    name: "JAZEERA THINNER 507",
    manufacturer: "Not specified",
    type: "Flammable, Health, Environment",
    expiry: "07/08/2028",
    status: "Valid",
    hazard: ["Flammable", "Health Hazard", "Hazardous to Environment"],
    sds: "",
    coshh: ""
  },
  {
    id: 37,
    name: "Permatex_MSDS_ 80003",
    manufacturer: "Not specified",
    type: "Toxic, Health",
    expiry: "08/08/2028",
    status: "Valid",
    hazard: ["Acute Toxicity", "Health Hazard"],
    sds: "",
    coshh: ""
  },
  {
    id: 38,
    name: "Polywater® Wax-Base",
    manufacturer: "Not specified",
    type: "Health",
    expiry: "09/08/2028",
    status: "Valid",
    hazard: ["Health Hazard"],
    sds: "",
    coshh: ""
  },
  {
    id: 39,
    name: "Select Prime 2K Etch Primer",
    manufacturer: "Not specified",
    type: "Flammable, Health, corrosive",
    expiry: "10/08/2028",
    status: "Valid",
    hazard: ["Flammable", "Health Hazard", "Corrosive"],
    sds: "",
    coshh: ""
  },
  {
    id: 40,
    name: "WELD-ON_714_ULVOC_US_en_2_0",
    manufacturer: "Not specified",
    type: "Health, Oxidizing",
    expiry: "11/08/2028",
    status: "Valid",
    hazard: ["Health Hazard", "Oxidizing"],
    sds: "",
    coshh: ""
  },
  {
    id: 41,
    name: "Zinc Spray",
    manufacturer: "Not specified",
    type: "Flammable, Environment, Health",
    expiry: "12/08/2028",
    status: "Valid",
    hazard: ["Flammable", "Hazardous to Environment", "Health Hazard"],
    sds: "",
    coshh: ""
  },
  {
    id: 42,
    name: "Flowcrete Base A",
    manufacturer: "Not specified",
    type: "Environment, Health, corrosive",
    expiry: "13/08/2028",
    status: "Valid",
    hazard: ["Hazardous to Environment", "Health Hazard", "Corrosive"],
    sds: "",
    coshh: ""
  },
  {
    id: 43,
    name: "FLOwCOAT - HARDENER B 7092602",
    manufacturer: "Not specified",
    type: "Environment, Health, corrosive",
    expiry: "14/08/2028",
    status: "Valid",
    hazard: ["Hazardous to Environment", "Health Hazard", "Corrosive"],
    sds: "",
    coshh: ""
  },
  {
    id: 44,
    name: "Nitomortar TC2000 Base",
    manufacturer: "Not specified",
    type: "Environmental, Health",
    expiry: "15/08/2028",
    status: "Valid",
    hazard: ["Hazardous to Environment", "Health Hazard"],
    sds: "",
    coshh: ""
  },
  {
    id: 45,
    name: "Nitomortar TC2000 Hardener",
    manufacturer: "Not specified",
    type: "EnvironmenT, Health, corrosive",
    expiry: "16/08/2028",
    status: "Valid",
    hazard: ["Hazardous to Environment", "Health Hazard", "Corrosive"],
    sds: "",
    coshh: ""
  },
  {
    id: 46,
    name: "ACRYLIC LACQUER THINNER",
    manufacturer: "Not specified",
    type: "Flammable, Environment, Health",
    expiry: "17/08/2028",
    status: "Valid",
    hazard: ["Flammable", "Hazardous to Environment", "Health Hazard"],
    sds: "",
    coshh: ""
  },
  {
    id: 47,
    name: "Stucco Putty Filler (JOTUN)",
    manufacturer: "Not specified",
    type: "Health",
    expiry: "18/08/2028",
    status: "Valid",
    hazard: ["Health Hazard"],
    sds: "",
    coshh: ""
  },
  {
    id: 48,
    name: "ACOUSTIC ACRYLIC SEALAND Fl RESEAL",
    manufacturer: "Not specified",
    type: "Health",
    expiry: "19/08/2028",
    status: "Valid",
    hazard: ["Health Hazard"],
    sds: "",
    coshh: ""
  },
  {
    id: 49,
    name: "STARK SPRAY PAINTS",
    manufacturer: "Not specified",
    type: "Flammable, Health",
    expiry: "20/08/2028",
    status: "Valid",
    hazard: ["Flammable", "Health Hazard"],
    sds: "",
    coshh: ""
  },
  {
    id: 50,
    name: "Flexible Fire Seal_ CICOGRIP",
    manufacturer: "Not specified",
    type: "Flammable, Health",
    expiry: "21/08/2028",
    status: "Valid",
    hazard: ["Flammable", "Health Hazard"],
    sds: "",
    coshh: ""
  },
  {
    id: 51,
    name: "WEBER",
    manufacturer: "Not specified",
    type: "Health",
    expiry: "22/08/2028",
    status: "Valid",
    hazard: ["Health Hazard"],
    sds: "",
    coshh: ""
  },
  {
    id: 52,
    name: "Flowcrete Deckshield - Base A",
    manufacturer: "Not specified",
    type: "Corrosive, Health",
    expiry: "23/08/2028",
    status: "Valid",
    hazard: ["Corrosive", "Health Hazard"],
    sds: "",
    coshh: ""
  },
  {
    id: 53,
    name: "Flowcrete Deckshield - Base B",
    manufacturer: "Not specified",
    type: "Health",
    expiry: "24/08/2028",
    status: "Valid",
    hazard: ["Health Hazard"],
    sds: "",
    coshh: ""
  },
  {
    id: 54,
    name: "Fenomastic My Home Rich Matt JOTUN",
    manufacturer: "Not specified",
    type: "Environment, Health",
    expiry: "25/08/2028",
    status: "Valid",
    hazard: ["Hazardous to Environment", "Health Hazard"],
    sds: "",
    coshh: ""
  },
  {
    id: 55,
    name: "JOTASHIELD ALKALI RESISTAN PRIMER CLASS OF HAZARD",
    manufacturer: "Not specified",
    type: "Environment, Health",
    expiry: "26/08/2028",
    status: "Valid",
    hazard: ["Hazardous to Environment", "Health Hazard"],
    sds: "",
    coshh: ""
  },
  {
    id: 56,
    name: "Jotun Jotashield Carbo",
    manufacturer: "Not specified",
    type: "Health",
    expiry: "27/08/2028",
    status: "Valid",
    hazard: ["Health Hazard"],
    sds: "",
    coshh: ""
  },
  {
    id: 57,
    name: "MAPEi ULTRATOP",
    manufacturer: "Not specified",
    type: "Health",
    expiry: "28/08/2028",
    status: "Valid",
    hazard: ["Health Hazard"],
    sds: "",
    coshh: ""
  },
  {
    id: 58,
    name: "FENOMASTIC EMULSION PRIMER",
    manufacturer: "Not specified",
    type: "Health",
    expiry: "29/08/2028",
    status: "Valid",
    hazard: ["Health Hazard"],
    sds: "",
    coshh: ""
  },
  {
    id: 59,
    name: "ANCHOR BOTTLE SPARY PAINT",
    manufacturer: "Not specified",
    type: "Flammable, Environment, Health",
    expiry: "30/08/2028",
    status: "Valid",
    hazard: ["Flammable", "Hazardous to Environment", "Health Hazard"],
    sds: "",
    coshh: ""
  },
  {
    id: 60,
    name: "BETCO TERAZZO",
    manufacturer: "Not specified",
    type: "Health",
    expiry: "31/08/2028",
    status: "Valid",
    hazard: ["Health Hazard"],
    sds: "",
    coshh: ""
  },
  {
    id: 61,
    name: "FILA INTERIOR RESINOUS",
    manufacturer: "Not specified",
    type: "Health",
    expiry: "01/09/2028",
    status: "Valid",
    hazard: ["Health Hazard"],
    sds: "",
    coshh: ""
  },
  {
    id: 62,
    name: "STRONGCOAT TERRAZZO BASE & HARDNER",
    manufacturer: "Not specified",
    type: "Flammable, Enviroment, Health, Corrosive",
    expiry: "02/09/2028",
    status: "Valid",
    hazard: ["Flammable", "Hazardous to Environment", "Health Hazard", "Corrosive"],
    sds: "",
    coshh: ""
  },
  {
    id: 63,
    name: "CARBOLINE RESINOUS TERRAZZO",
    manufacturer: "Not specified",
    type: "Health",
    expiry: "03/09/2028",
    status: "Valid",
    hazard: ["Health Hazard"],
    sds: "",
    coshh: ""
  },
  {
    id: 64,
    name: "JAZEERA MASHASHCO",
    manufacturer: "Not specified",
    type: "Health",
    expiry: "04/09/2028",
    status: "Valid",
    hazard: ["Health Hazard"],
    sds: "",
    coshh: ""
  },
  {
    id: 65,
    name: "FLOWFAST 319 FLEXIBLE SEAL CLEAR",
    manufacturer: "Not specified",
    type: "Corrosive, Health",
    expiry: "05/09/2028",
    status: "Valid",
    hazard: ["Corrosive", "Health Hazard"],
    sds: "",
    coshh: ""
  },
  {
    id: 66,
    name: "TEST CHEMICAL",
    manufacturer: "Not specified",
    type: "Corrosive, Health",
    expiry: "06/09/2028",
    status: "Valid",
    hazard: ["Corrosive", "Health Hazard"],
    sds: "",
    coshh: ""
  }
];
